### ISSUE TITLE
Says "No change" even when there is a change

### ISSUE THREAD

**Issue by Infinality** [jpillora/webproc#1]
Nice utility!  I have it set up with dnsmasq, with everything running as root.  When I make a modification to the configuration file through the web UI, and try to save it, I get a red box that says "No change", even though a change was made.

**Comment by jpillora** [comment]
Does the file change on disk? OS? Arch?

**Comment by Infinality** [comment]
Sorry, it was on RHEL7 64-bit.  Nothing else is modifying the file.  It happened when I had multiple files set for ConfigurationFiles=["file1","file2"].  Under certain conditions the files did seem to save even though it said "no change".  Other times, they didn't save.  I can try to see if there is a pattern if that would be helpful.

**Comment by jpillora** [comment]
Could you try with a single file?

**Comment by Infinality** [comment]
It seems to work perfectly when I only use a single configuration file.

**Comment by jpillora** [comment]
Okay looks like its related to multiple config files, will investigate
