### ISSUE TITLE
I can not build it successfully 

### ISSUE THREAD

**Issue by muratbulbul** [jpillora/webproc#12]
#$GOPATH/bin/webproc

  Usage: webproc [options]

  Options:
  --host  listening interface
  --port  listening port
  --user  basic auth username
  --pass  basic auth password

  Version:
    0.0.0-src

  Error:
    field 'ProgramArgs' invalid opts mode 'arglist'

During the install step:

# go generate ./...
agent/agent.go:1: running "statik": exec: "statik": executable file not found in $PATH

I got this error. 

How to build it perfectly?

**Comment by jpillora** [comment]
Sorry this should be in the docs

statik is https://github.com/rakyll/statik

go get github.com/rakyll/statik

**Comment by muratbulbul** [comment]
I am using the following process but still the same error occurs. 



# setup go, get go-bindata and webproc
$ go get -u github.com/jteeuwen/go-bindata/...
$ go get -u -v github.com/jpillora/webproc
$ go get -u -v  github.com/rakyll/statik
$ cd $GOPATH/src/github.com/jpillora/webproc
# ... edit source ...
$ go generate ./...
$ go install -v
$ $GOPATH/bin/webproc

**Comment by muratbulbul** [comment]
As I see, there is a issue with these lines at config.go 

Any idea?


//Config is shared for both toml unmarshalling and opts CLI generation
type Config struct {
        Host               string   `help:"listening interface"`
        Port               int      `help:"listening port" env:"PORT"`
        User               string   `help:"basic auth username" env:"HTTP_USER"`
        Pass               string   `help:"basic auth password" env:"HTTP_PASS"`
        AllowedIPs         []string `opts:"-"`
        **ProgramArgs**        []string `type:"arglist" min:"1" name:"args" help:"args can be either a command with arguments or a webproc file"`
        Log                Log      `opts:"-"`
        OnExit             OnExit   `help:"process exit action" default:"ignore"`
        ConfigurationFiles []string `name:"config" type:"commalist" help:"comma-separated list of configuration files"`
        RestartTimeout     Duration `opts:"-"`
        MaxLines           int      `help:"maximum number of log lines to show in webui" default:"5000"`
}


After installation:

# $GOPATH/bin/webproc

  Usage: webproc [options]

  Options:
  --host  listening interface
  --port  listening port
  --user  basic auth username
  --pass  basic auth password

  Version:
    0.0.0-src

  **Error:
    field 'ProgramArgs' invalid opts mode 'arglist'**

**Comment by jpillora** [comment]
It's using the wrong version of opts, I'll push a fix today

**Comment by muratbulbul** [comment]
Thanx you for your quick reply.

**Comment by muratbulbul** [comment]
Did you push new version?

**Comment by jpillora** [comment]
yep https://github.com/jpillora/webproc/commit/0e15e52a21ef4e759f0110b7686b89856ade5c9a
