### ISSUE TITLE
Add option to avoid restart on file save

### ISSUE THREAD

**Issue by dchidell** [jpillora/webproc#13]
Currently when saving config files it auto-restarts the process, this is often undesirable, especially as there is a restart button right next to it which can be used.

Some configuration files are picked up automatically by services without a restart being required. Alternatively it's often useful to ensure that a service won't be disrupted so the change can be made and a restart issued later.

**Comment by jpillora** [comment]
A reasonable request, not sure when I'll get time to do this though - would
you be able to send a PR?

**Comment by dchidell** [comment]
Created PR #14 . Never touched go before so might need some tweaking! Also updated some docs around configuration options.
