### ISSUE TITLE
Can not find package jsonpatch

### ISSUE THREAD

**Issue by port22** [jpillora/webproc#18]
I highly want to test this fine piece of software, but go stops on installing:

```
FROM golang:latest 
RUN go get github.com/jpillora/webproc

package gomodules.xyz/jsonpatch/v2: cannot find package "gomodules.xyz/jsonpatch/v2" in any of:
	/usr/local/go/src/gomodules.xyz/jsonpatch/v2 (from $GOROOT)
	/go/src/gomodules.xyz/jsonpatch/v2 (from $GOPATH)
```

Not really experienced in Go ... some dependency declaration missed ?

**Comment by jpillora** [comment]
Very annoying - I am always hesitant about using modules from domains other
than GitHub for this reason

Need to update the module reference in webproc
Or jsonpatch needs to restore this URL

**Comment by port22** [comment]
aah I see, didn't realized that offroad domain :-D 

https://godoc.org/gomodules.xyz/jsonpatch
seems v2 is abandoned in favor of v3.

can you update the deps?

**Comment by port22** [comment]
what about that: https://github.com/gomodules/jsonpatch

**Comment by port22** [comment]
I just tested your velox with jsonpatch v3 and webproc now installs fine and opened a PR https://github.com/jpillora/velox/pull/7

you may choose now what satisfies you the most ;-)

**Comment by port22** [comment]
just confirming that installation now works fine , thanks for merging!
