### ISSUE TITLE
Handle or strip ANSI color

### ISSUE THREAD

**Issue by spike008t** [jpillora/webproc#8]
Hey!

On log view, is it possible to support ansi colors?
If too complicated, why not to strip it first, and manage it later?

Example: 
```
\u001b[40m\u001b[37mdbug\u001b[39m\u001b[22m\u001b[49m
```
display 
![capture d ecran 2018-05-23 a 09 38 00](https://user-images.githubusercontent.com/262459/40410061-0c92d3e6-5e6d-11e8-96c0-70371fe80892.png)

**Comment by jpillora** [comment]
It would indeed be nice. Instead of that, I think I'd swap from using a
text editor as the log viewer to using something like hterm (making it like
read-only gotty <https://github.com/yudai/gotty>, however with pipes
attached to a file instead of the shell).
